### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by Solido** [fluttercommunity/flutter_infinite_listview#1]
Hi !
Do you want it to be added to the F.List or is there some tech stuffs to review ?
Thx

**Comment by jeroen-meijer** [comment]
Hey,

Thanks for your comment.
Usually, if repositories are not listed in the table on /community, are not compatible with both Android and iOS or need further development, they are not ready to be released and featured on Flutter Community.

I don’t know much about this particular package though, so other mods could prove me wrong, but that’s usually how it goes with still-in-development packages on FC.

If you want to use it, though, go ahead.

~ Jeroen (FC Mod)

**Comment by Solido** [comment]
Thank you @jeroen-meijer for the quick response !

**Comment by slightfoot** [comment]
@Solido This one can be released on the Awesome F.List. Its Dart only!

**Comment by slightfoot** [comment]
This should now be listed on the community table now.
