### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by lifenautjoe** [fluttercommunity/flutter_infinite_listview#2]
From the example and README I see no reason why someone should use this instead of a regular `ListView.builder`. 

Could you please clarify what usecases are there for this? 

Thanks!

**Comment by slightfoot** [comment]
A simple example is a calendar list where each entry in the List is a date, time being the infinite series.

ListView cannot go into a negative direction, so they do not contain the same functionality. Even if you try to resolve that with a hack like creating a regular ListView and set its starting scroll position to 10,000 pixels you need to then have fixed height items. This is resolves this issue and allows you to have variable height items.

**Comment by lifenautjoe** [comment]
Ahá! Amazing.

Thank you for explaining. I think if this would be somewhere in the readme
it would gain way more deserved appreciation.


Cheers,
Joel.

**Comment by jeroen-meijer** [comment]
Glad this is cleared up 😊
We’ll take your advice into consideration. Thanks for the feedback!

Closing this
