### ISSUE TITLE
Possible to use in a CustomScrollView with SliverAppBar

### ISSUE THREAD

**Issue by stargazing-dino** [fluttercommunity/flutter_infinite_listview#3]
Hi!

I want to put an `InifiniteListView` inside a `CustomScrollView` so that I can get an appbar that will go in and out of view but I think to have a list inside the scroll view, it needs to be a `SliverList` or at least extend `SliverMultiBoxAdaptorWidget`

**Comment by stargazing-dino** [comment]
Something like the `loading_more_list` library has [here](https://github.com/fluttercandies/loading_more_list/blob/master/lib/src/loading_more_sliver_list.dart) but without the complexity their api has. This library is lot simpler to understand in my opinion.

**Comment by RicardoRB** [comment]
@Nolence Any new?

**Comment by raulmabe** [comment]
@Nolence  Have you tried to use the existing list in a NestedScrollView?

**Comment by stargazing-dino** [comment]
I honestly forgot what the context for this question was. I'm going to assume `NestedScrollView` would handle the original issue though. I'm closing for now but feel free to ping and I'll reopen
