### ISSUE TITLE
Infinite listview not listening to NeverScrollableScrollPhysics

### ISSUE THREAD

**Issue by rubenvde** [fluttercommunity/flutter_infinite_listview#5]
This will not prevent the InfiniteListView from scrolling which is not the expected behaviour: 
`InfiniteListView.builder(physics: NeverScrollableScrollPhysics())`

**Comment by CEichmueller** [comment]
Yeah the problem lies in this part: final scrollPhysics = AlwaysScrollableScrollPhysics(parent: physics) which is within the infinite_listview.dart. This needs to be changed

**Comment by slightfoot** [comment]
Fixed as of v1.1.0
