### ISSUE TITLE
How to specify limits at runtime?

### ISSUE THREAD

**Issue by renjipanicker** [fluttercommunity/flutter_infinite_listview#6]
Apologies if this is too obvious, but how does one handle a situation where we do not know the total number of items, so we keep scrolling up (or down) until the remote REST server returns no-more-data?

All the sample code I have seen so far is truly infinite, without any upper or lower limits.

How do we set the limits at the time of fetching new data?
Thanks.

**Comment by marcglasberg** [comment]
This widget is for infinite lists. So you shouldn't use it for what you just described. Try a regular ListView.

**Comment by renjipanicker** [comment]
I had my suspicion that might be the case, thanks for confirming!
