### ISSUE TITLE
Combine with the scrollable_positioned_list pacakge

### ISSUE THREAD

**Issue by kansson** [fluttercommunity/flutter_infinite_listview#7]
Is it possible to combine the package with the [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list) package? 
The features I'm looking to combine from the packages is the infinite scrolling and the listener of the currently visible items in the list.

Issue in the other package: [#75](https://github.com/google/flutter.widgets/issues/75)

**Comment by jangruenwaldt** [comment]
Would be cool, but for now could use the scrollable_positioned_list with itemCount: 10K
