### ISSUE TITLE
Preventing negative index?

### ISSUE THREAD

**Issue by hansolowireless** [fluttercommunity/flutter_infinite_listview#9]
Thank you for this great package!

I have implemented it for an Android TV app in a vertical set of horizontal rows, forming a grid. 

The issue I am finding is that focus lets me scroll horizontally from the '0' index to the left, so I am getting to a negative index (-1), and I get a blank space in the row.

How could I prevent focus going to this negative index? Thanks!

**Comment by slightfoot** [comment]
If you don't want negative index.. then you just use a normal ListView.builder without a itemCount.
